# Generated by Django 2.0.5 on 2018-05-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.CharField(default='02/06/1990', max_length=255),
            preserve_default=False,
        ),
    ]
