# Generated by Django 2.0.5 on 2018-05-21 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_auto_20180521_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotable',
            name='all_quotes',
        ),
        migrations.RemoveField(
            model_name='quotable',
            name='users',
        ),
        migrations.AddField(
            model_name='quotable',
            name='user_quotes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='quote.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotable',
            name='users_liked',
            field=models.ManyToManyField(related_name='favorite_quote', to='quote.User'),
        ),
    ]
