# Generated by Django 2.0.5 on 2018-05-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_auto_20180521_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotable',
            name='date',
        ),
        migrations.AddField(
            model_name='quotable',
            name='quoted_by',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
